---

version: "3.9"
services:
  postgres:
    image: "${POSTGRES_IMAGE}"
    environment:
      POSTGRES_USER: galaxy
      POSTGRES_PASSWORD: galaxy
  rabbitmq:
    image: "${RABBITMQ_IMAGE}"
  galaxy-web:
    depends_on:
      - "postgres"
      - "rabbitmq"
    image: galaxy-pulsar-dev:galaxy-web
    build:
      context: "./galaxy/context"
      dockerfile: "Dockerfile.web"
      args:
        GALAXY_IMAGE: "${GALAXY_IMAGE}"
        UID: "${UID}"
        GID: "${GID}"
    #user: "${UID}:${GID}"
    #command: uwsgi --yaml config/galaxy.yml
    volumes: &galaxy_volumes
      - "${GALAXY_ROOT}:/galaxy"
      - "./galaxy/database:/galaxy/database"
      - "./galaxy/venv:/galaxy/.venv:ro"
      - "./galaxy/config:/galaxy/config:ro"
      - "./galaxy/rule.py:/galaxy/lib/galaxy/jobs/rules/rule.py:ro"
    ports:
      - "8080:8080"
  galaxy-job:
    depends_on:
      - "postgres"
      - "rabbitmq"
    image: galaxy-pulsar-dev:galaxy-job
    build:
      context: "./galaxy/context"
      dockerfile: "Dockerfile.job"
      args:
        GALAXY_IMAGE: "${GALAXY_IMAGE}"
        UID: "${UID}"
        GID: "${GID}"
    #command: python3 scripts/galaxy-main --attach-to-pool=job-handlers
    volumes: *galaxy_volumes
    environment:
      GALAXY_CONFIG_OVERRIDE_CONDA_INIT: 'false'
  pulsar:
    depends_on:
      - "rabbitmq"
    image: galaxy-pulsar-dev:pulsar
    build:
      context: "./pulsar/context"
      args:
        PULSAR_IMAGE: "${PULSAR_IMAGE}"
        UID: "${UID}"
        GID: "${GID}"
    #command: pulsar-main
    volumes:
      - "${GALAXY_ROOT}:/remote-galaxy:ro"
      - "./remote-galaxy/venv:/remote-galaxy/.venv:ro"
      - "${PULSAR_ROOT}:/pulsar"
      - "./pulsar/var:/pulsar/var"
      - "./pulsar/venv:/pulsar/.venv:ro"
      - "./pulsar/config/app.yml:/pulsar/app.yml:ro"
      # To use Galaxy's Conda instead (also adjust resolvers in pulsar/config/app.yml)
      #- "./galaxy/database/dependencies/_conda:/galaxy/database/dependencies/_conda:ro"
      # To use the remote_copy transfer action instead of remote_transfer (also set in galaxy/config/pulsar_actions.yml)
      #- "./galaxy/database:/galaxy/database"
